services:
  get_data:
    build:
      context: .
      dockerfile: ../countries-population-service/Dockerfile
    command: >
      sh -c "
        cp .env.example .env &&
        alembic upgrade head &&
        python -m app.main get_data
      "
    depends_on:
      db:
        condition: service_healthy

  print_data:
    build:
      context: .
      dockerfile: ../countries-population-service/Dockerfile
    command: >
      sh -c "
        cp .env.example .env &&
        python -m app.main print_data
      "
    depends_on:
      db:
        condition: service_healthy

  db:
    image: 'postgres:latest'
    container_name: db
    env_file:
      - .env.example
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql:/docker-entrypoint-initdb.d
      - ./var/lib/postgresql:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB -h 127.0.0.1 || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
